### ISSUE TITLE
Allow ca-certificates to add truststore.jks or keystore.jks to the expected Java trust store locations

### ISSUE THREAD

**Issue by voor** [paketo-buildpacks/ca-certificates#145]
## Describe the Enhancement

CA certificates generally exist in the format of PEM encoded certificates, there is also sometimes a strong requirement for Java (or other JVM originating languages) to have their certificates stored in another format and in another location.

## Possible Solution

In containers you can achieve this by importing the associated JKS files into the existing trustore -- *if it exists* these trust stores are stored in well known locations _generally_ (which should be almost a guarantee in the case of buildpacks.

## Motivation

Inside of a Java application sometimes you are making HTTP calls that require TLS, and these certificates that exist in the ca-certificates are not looked at, instead it looks at the files in the Java trust store.

**Comment by dmikusa** [comment]
When you use `ca-certificates` in conjunction with a `libjvm` based buildpack, the JVM's keystores should be updated in sync with `ca-certificates` buildpack. So when you add a trusted cert with `ca-certificates`, the `libjvm` based buildpack should see that, because it sees all of the system trusted certs, and it should make that available to the JVM.

Are you seeing a different behavior?

**Comment by voor** [comment]
Oh neat, didn't realize it did that.  Would a similar trick be possible for private certs that are bound in to provide them to a mounted keystore?

**Comment by dmikusa** [comment]
I don't believe that we do anything with private key files. The existing code is meant to basically import trusted CA certs from the system into the JVM keystore, thus keeping the two in sync. It's not really meant for private keys because it would be putting them in the JVM's default keystore.

If possible, I would suggest trying to not depend on the system keystore for storing private keys. 12-factor style says you should include resources like that with your application as it'll make your app less dependent on the system and more portable. You can bundle a separate keystore with your application that contains just the required private keys, then load that in code when it's needed.

If you can't do that, maybe the app needs the keys in the default keystore, you could bundle the keystore with your app (or map it into the container) and add the JVM flag to change the default keystore to point to the one you bundle/map. The JVM has separate flags for the [default keystore and truststore](https://stackoverflow.com/a/9838372/1585136), so overriding the default keystore shouldn't impact the ability to trust certs. Also, I believe the default keystore has no private keys, so bundling your own and changing the default shouldn't lose anything for you.

**Comment by Mcfloy** [comment]
Although this ticket is closed I might give my two cents to at least describe a situation that would be favorable to this issue.

Let's say you need to use a message queue service (Kafka for example but could be everything) but you have to use a custom key store and trust store to "identify" yourself to the server. You could pass these files with the -D parameters and it could work.

But here's the trick, the key store and the trust store are secured with a password. And you might just use the -Djavax.net.ssl.keystorePassword but in your logs this might appear and you wouldn't want to.

Secured key store and trust store are not a use case you might want to handle, but it might help remove unsecure tweaks at the end of the pipeline.

**Comment by dmikusa** [comment]
@Mcfloy If you need to password protect a key, you shouldn't be putting that key into the default keystore. I also agree that setting `-Djavax.net.ssl.*` properties are not the way to do this (IMHO, you almost never want to set those). In either case, you're bypassing your key's password protection. If someone is able to get to the point where they can read that file off disk, they'll be able to without hardly any trouble at all bypass the password and get your key.

For your use case (or any case where your app requires a key file), what I would suggest is this:

1. You make your own keystore with your client cert & key. Password protect it.
2. You provide that to your application in a secure manner, possibly as a K8s config map if you're using K8s or from a config server.
3. You pass the credentials for the keystore through to your app in the same way you pass all secure credentials (K8s secret, password vault, etc... Ideally something where the password is only in memory). Your app reads that securely and opens the keystore.
4. You load the keystone in your application when it is required by your application using the password you obtained (or configure your client to use that file directly, if that is an option).

I'm sure there are other ways to do this as well, but you don't want to modify the default keystore as it has a standard password everyone knows.
