### ISSUE TITLE
Buildpack fails when an empty certificate file is passed.

### ISSUE THREAD

**Issue by coolgang123** [paketo-buildpacks/ca-certificates#246]
Buildpack fails when an empty certificate file is passed.

## Expected Behavior
Ignore empty files silently instead of failing.

## Current Behavior
Fails with following error:

```
failed to split certificates at path /cnb/bindings/cacerts/my-empty.pem 
failed to decode PEM data
```

## Possible Solution
Ignore empty files silently

## Steps to Reproduce
Pass in an empty .pem file to be added during run time.

**Comment by coolgang123** [comment]
Pull request: https://github.com/paketo-buildpacks/ca-certificates/pull/247

**Comment by dmikusa** [comment]
I'm not sold on this, I can see it being useful both ways. Can you expand on the need here? What is the significance of an empty file? Why should we skip it versus generating an error?

Counter-point. Throwing an error fails fast and lets someone know that there is an file, because you wouldn't typically see an empty PEM file. I'd go so far as to say an empty PEM file is not correct.

**Comment by dsboulder** [comment]
We've got an app with a binding to a set of trusted CAs provided by a separate team. It's really valuable for us to always bind to that list, even if it's empty, because then we don't need to peer inside of the secret and try to determine if we should or shouldn't bind it

**Comment by coolgang123** [comment]
The reasoning makes sense. We will find alternative solution for our issue. Closing the issue.
